//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebAppClient.StudentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseField;
        
        private int messageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                if ((object.ReferenceEquals(this.responseField, value) != true)) {
                    this.responseField = value;
                    this.RaisePropertyChanged("response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                if ((this.messageIdField.Equals(value) != true)) {
                    this.messageIdField = value;
                    this.RaisePropertyChanged("messageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.StudentServiceSoap")]
    public interface StudentServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        StudentWebAppClient.StudentService.GetStudentByIdResponse GetStudentById(StudentWebAppClient.StudentService.GetStudentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByIdResponse> GetStudentByIdAsync(StudentWebAppClient.StudentService.GetStudentByIdRequest request);
        
        // CODEGEN: Generating message contract since element name lastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentByPersonId", ReplyAction="*")]
        StudentWebAppClient.StudentService.GetStudentByPersonIdResponse GetStudentByPersonId(StudentWebAppClient.StudentService.GetStudentByPersonIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentByPersonId", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByPersonIdResponse> GetStudentByPersonIdAsync(StudentWebAppClient.StudentService.GetStudentByPersonIdRequest request);
        
        // CODEGEN: Generating message contract since element name lastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentAuthentication", ReplyAction="*")]
        StudentWebAppClient.StudentService.GetStudentAuthenticationResponse GetStudentAuthentication(StudentWebAppClient.StudentService.GetStudentAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentAuthenticationResponse> GetStudentAuthenticationAsync(StudentWebAppClient.StudentService.GetStudentAuthenticationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentById", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentByIdRequestBody Body;
        
        public GetStudentByIdRequest() {
        }
        
        public GetStudentByIdRequest(StudentWebAppClient.StudentService.GetStudentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetStudentByIdRequestBody() {
        }
        
        public GetStudentByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentByIdResponseBody Body;
        
        public GetStudentByIdResponse() {
        }
        
        public GetStudentByIdResponse(StudentWebAppClient.StudentService.GetStudentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentWebAppClient.StudentService.Student GetStudentByIdResult;
        
        public GetStudentByIdResponseBody() {
        }
        
        public GetStudentByIdResponseBody(StudentWebAppClient.StudentService.Student GetStudentByIdResult) {
            this.GetStudentByIdResult = GetStudentByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByPersonIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByPersonId", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentByPersonIdRequestBody Body;
        
        public GetStudentByPersonIdRequest() {
        }
        
        public GetStudentByPersonIdRequest(StudentWebAppClient.StudentService.GetStudentByPersonIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByPersonIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public GetStudentByPersonIdRequestBody() {
        }
        
        public GetStudentByPersonIdRequestBody(int id, string lastName) {
            this.id = id;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByPersonIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByPersonIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentByPersonIdResponseBody Body;
        
        public GetStudentByPersonIdResponse() {
        }
        
        public GetStudentByPersonIdResponse(StudentWebAppClient.StudentService.GetStudentByPersonIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByPersonIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentWebAppClient.StudentService.Student GetStudentByPersonIdResult;
        
        public GetStudentByPersonIdResponseBody() {
        }
        
        public GetStudentByPersonIdResponseBody(StudentWebAppClient.StudentService.Student GetStudentByPersonIdResult) {
            this.GetStudentByPersonIdResult = GetStudentByPersonIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentAuthentication", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentAuthenticationRequestBody Body;
        
        public GetStudentAuthenticationRequest() {
        }
        
        public GetStudentAuthenticationRequest(StudentWebAppClient.StudentService.GetStudentAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public GetStudentAuthenticationRequestBody() {
        }
        
        public GetStudentAuthenticationRequestBody(int id, string lastName) {
            this.id = id;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentAuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentWebAppClient.StudentService.GetStudentAuthenticationResponseBody Body;
        
        public GetStudentAuthenticationResponse() {
        }
        
        public GetStudentAuthenticationResponse(StudentWebAppClient.StudentService.GetStudentAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentWebAppClient.StudentService.ResponseMessage GetStudentAuthenticationResult;
        
        public GetStudentAuthenticationResponseBody() {
        }
        
        public GetStudentAuthenticationResponseBody(StudentWebAppClient.StudentService.ResponseMessage GetStudentAuthenticationResult) {
            this.GetStudentAuthenticationResult = GetStudentAuthenticationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentServiceSoapChannel : StudentWebAppClient.StudentService.StudentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceSoapClient : System.ServiceModel.ClientBase<StudentWebAppClient.StudentService.StudentServiceSoap>, StudentWebAppClient.StudentService.StudentServiceSoap {
        
        public StudentServiceSoapClient() {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWebAppClient.StudentService.GetStudentByIdResponse StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentById(StudentWebAppClient.StudentService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentById(request);
        }
        
        public StudentWebAppClient.StudentService.Student GetStudentById(int id) {
            StudentWebAppClient.StudentService.GetStudentByIdRequest inValue = new StudentWebAppClient.StudentService.GetStudentByIdRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentByIdRequestBody();
            inValue.Body.id = id;
            StudentWebAppClient.StudentService.GetStudentByIdResponse retVal = ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentById(inValue);
            return retVal.Body.GetStudentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByIdResponse> StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentByIdAsync(StudentWebAppClient.StudentService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByIdResponse> GetStudentByIdAsync(int id) {
            StudentWebAppClient.StudentService.GetStudentByIdRequest inValue = new StudentWebAppClient.StudentService.GetStudentByIdRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentByIdRequestBody();
            inValue.Body.id = id;
            return ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWebAppClient.StudentService.GetStudentByPersonIdResponse StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentByPersonId(StudentWebAppClient.StudentService.GetStudentByPersonIdRequest request) {
            return base.Channel.GetStudentByPersonId(request);
        }
        
        public StudentWebAppClient.StudentService.Student GetStudentByPersonId(int id, string lastName) {
            StudentWebAppClient.StudentService.GetStudentByPersonIdRequest inValue = new StudentWebAppClient.StudentService.GetStudentByPersonIdRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentByPersonIdRequestBody();
            inValue.Body.id = id;
            inValue.Body.lastName = lastName;
            StudentWebAppClient.StudentService.GetStudentByPersonIdResponse retVal = ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentByPersonId(inValue);
            return retVal.Body.GetStudentByPersonIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByPersonIdResponse> StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentByPersonIdAsync(StudentWebAppClient.StudentService.GetStudentByPersonIdRequest request) {
            return base.Channel.GetStudentByPersonIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentByPersonIdResponse> GetStudentByPersonIdAsync(int id, string lastName) {
            StudentWebAppClient.StudentService.GetStudentByPersonIdRequest inValue = new StudentWebAppClient.StudentService.GetStudentByPersonIdRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentByPersonIdRequestBody();
            inValue.Body.id = id;
            inValue.Body.lastName = lastName;
            return ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentByPersonIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWebAppClient.StudentService.GetStudentAuthenticationResponse StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentAuthentication(StudentWebAppClient.StudentService.GetStudentAuthenticationRequest request) {
            return base.Channel.GetStudentAuthentication(request);
        }
        
        public StudentWebAppClient.StudentService.ResponseMessage GetStudentAuthentication(int id, string lastName) {
            StudentWebAppClient.StudentService.GetStudentAuthenticationRequest inValue = new StudentWebAppClient.StudentService.GetStudentAuthenticationRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentAuthenticationRequestBody();
            inValue.Body.id = id;
            inValue.Body.lastName = lastName;
            StudentWebAppClient.StudentService.GetStudentAuthenticationResponse retVal = ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentAuthentication(inValue);
            return retVal.Body.GetStudentAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentAuthenticationResponse> StudentWebAppClient.StudentService.StudentServiceSoap.GetStudentAuthenticationAsync(StudentWebAppClient.StudentService.GetStudentAuthenticationRequest request) {
            return base.Channel.GetStudentAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWebAppClient.StudentService.GetStudentAuthenticationResponse> GetStudentAuthenticationAsync(int id, string lastName) {
            StudentWebAppClient.StudentService.GetStudentAuthenticationRequest inValue = new StudentWebAppClient.StudentService.GetStudentAuthenticationRequest();
            inValue.Body = new StudentWebAppClient.StudentService.GetStudentAuthenticationRequestBody();
            inValue.Body.id = id;
            inValue.Body.lastName = lastName;
            return ((StudentWebAppClient.StudentService.StudentServiceSoap)(this)).GetStudentAuthenticationAsync(inValue);
        }
    }
}
